# Generated by Django 4.2.27 on 2026-02-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useraccount_chat_enabled_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
