# Generated by Django 6.0.1 on 2026-02-02 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useraccount_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='api.useraccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='api.useraccount'),
        ),
    ]
